apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sentiment-analysis
  name: sentiment-analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sentiment-analysis
  template:
    metadata:
      labels:
        app: sentiment-analysis
    spec:
      containers:
        - image: thekenken/challenge-soyhuce-mlops:latest
          name: sentiment-analysis
          imagePullPolicy: Always
          env:
            - name: TF_SERVER_URL
              value: "http://tf-server:8501/"
          ports:
            - containerPort: 5000
              name: sentiment-analysis
