apiVersion: v1
kind: Service
metadata:
  labels:
    app: tf-server
  name: tf-server
spec:
  type: LoadBalancer
  ports:
  - name: tf-server-service
    port: 8501
    targetPort: 8501
  selector:
    app: tf-server
